### PR TITLE
Improve code readability

### PR DESCRIPTION
**Pull request by emielmolenaar**
Improve code readability. Force some PSR-2 code style. Say hello to braces. Say goodbye to useless comments.

### CODE REVIEW

**Comment by olscore** [comment]
Do to the size of the commit (22 files) I will have to individually break this down and review file-by-file to ensure it is not breaking anything. Looks like it was sent through a style parser? Anyways, thanks.

**Comment by emielmolenaar** [comment]
Just some PhpStorm magic, and maybe some inspiration for you :)

**Comment by OddGreg** [comment]
While I understand the purpose of emiel's pull request, I would not accept it in its totality. 1) It is too large, 2) some formatting choices are opinionated and not particularly useful (long list of array values, for one, is somewhat pedantic), and 3) it is offered without first requesting or offering a code format standard (other than simply pointing to PSR-2 style guide which is, at best, an informed suggestion and not uniformly adopted) - which in itself would have been a courtesy to the author, and an opportunity to open a dialog.

In addition, the title of the PR is argumentative rather than informative. Just my opinion.

**Comment by olscore** [comment]
I agree @OddGreg ... Just didn't really want to say as much. Looking over PSR-2 the standards seem arbitrary and odd. Code styling being voted on by "celebrity coders" isn't really a valid reason to change the styling in this or any other project for that matter. Actually I have seen a thousand different ways to code, styling standards, etc. The current styling is similar to Python, aiming to avoid brackets because I happen to find that more readable and I am the only developer on this at the moment. So no other style guide has been presented or discussed (which I am open to discussing, generally...) 

Also I personally dislike PSR-2 because it reminds me too much of common jQuery / JS styling which is an easy mental note for me in "switching gears" between JS to PHP code. The excessive comments are intended for beginners and also new persons to PHP, i.e., programmers who may be familiar with OOP and other languages but unfamiliar with PHP. I don't really see the comments as an issue because most of the helpers, libraries, and vendor classes will hardly be edited frequently enough to matter much.

As stated by @OddGreg the parser seems to have made some things less readable (e.g., long arrays) and in some cases messed up comments. It is also generally too long or too much. I don't really want to get into a styling argument, but I think PSR-2 is much less readable, and also an arbitrary standard.

Thank you for your commentary, both of you.

**Comment by olscore** [comment]
@emielmolenaar You'll be happy to know I have adopted PSR-2 for this project. The issue about over commenting I have not addressed and will leave in-tact as I plan to create tutorials for newbies and I do think the over-commenting can help some persons looking to dig into the underlying components.

**Pull request closed without merging**
